FROM container-registry.oracle.com/graalvm/jdk:23 AS build
COPY . /webserver
WORKDIR /webserver
RUN ./mvnw clean package

# Debian Slim image with JDK
FROM debian:12-slim
COPY --from=build /webserver/target/webserver-0.0.1-SNAPSHOT.jar webserver-0.0.1-SNAPSHOT.jar  
EXPOSE 8080  
ENTRYPOINT ["java", "-jar", "webserver-0.0.1-SNAPSHOT.jar"]