FROM container-registry.oracle.com/graalvm/native-image:23-muslib AS nativebuild
# FROM --platform=linux/g container-registry.oracle.com/graalvm/native-image:23-muslib AS nativebuild
COPY . /webserver
WORKDIR /webserver

# Install and use UPX
ARG UPX_VERSION=4.2.2
ARG UPX_ARCHIVE=upx-${UPX_VERSION}-amd64_linux.tar.xz
RUN microdnf -y install wget xz && \
    wget -q https://github.com/upx/upx/releases/download/v${UPX_VERSION}/${UPX_ARCHIVE} && \
    tar -xJf ${UPX_ARCHIVE} && \
    rm -rf ${UPX_ARCHIVE} && \
    mv upx-${UPX_VERSION}-amd64_linux/upx . && \
    rm -rf upx-${UPX_VERSION}-amd64_linux

# Build a fully static native image with optimization for size
RUN  ./mvnw -Dmaven.test.skip=true -Pnative,fully-static native:compile
RUN ls -lh /webserver/target
RUN ./upx --lzma --best -o /webserver/webserver.static-upx /webserver/target/webserver.static

# Scratch--fully static and compressed
FROM scratch
WORKDIR /tmp
COPY --from=nativebuild /webserver/webserver.static /
EXPOSE 8000
ENTRYPOINT ["/webserver.static-upx", "-b", "0.0.0.0", "-d", "/web"]

# FROM scratch
# WORKDIR /tmp
# COPY target/webserver.static-upx /
# EXPOSE 8080
# ENTRYPOINT ["/webserver.static-upx"]