FROM container-registry.oracle.com/graalvm/native-image:23 AS nativebuild
COPY . /webserver
WORKDIR /webserver
# Build a dynamically linked native image with optimization for size
RUN ./mvnw -Dmaven.test.skip=true -Pdynamic-size-optimized native:compile

# Distroless Java Base-provides glibc and other libraries needed by the JDK
FROM gcr.io/distroless/java-base-debian12
COPY --from=nativebuild /webserver/target/webserver.dynamic-optimized /
EXPOSE 8000
ENTRYPOINT ["/webserver.dynamic-optimized", "-b", "0.0.0.0", "-d", "/web"]

# FROM gcr.io/distroless/java-base-debian12
# COPY target/webserver.dynamic-optimized /
# EXPOSE 8080
# ENTRYPOINT ["/webserver.dynamic-optimized"]