name: Github Actions Pipeline
on: [push, pull_request]
jobs:
  build:
    name: Run webserver
    runs-on: ubuntu-latest
    timeout-minutes: 30    
    steps:
    - uses: actions/checkout@v4
    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '24-ea'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Spring Boot Web Server
      run: |
        # # Build JAR (Debian Slim)
        # ./build-jar-java-base.sh
        # ./build-jar-slim.sh
        # #

        # # Build Jlink custom runtime (Distroless Java Base)
        # ./build-jlink.sh
        # #

        # # Build dynamic image (Distroless Java Base)
        # ./build-dynamic-image.sh
        # #

        # # Build dynamic image, optimized for size (Distroless Java Base)
        # ./build-dynamic-image-optimized.sh
        # #
        
        # # Setup musl toolchain
        # ./setup-musl.sh
        # export PATH="$PWD/musl-toolchain/bin:$PATH"
        # #

        # # Build mostly static image (Distroless Base)
        # ./build-mostly-static-image.sh
        # #

        # # Build fully static image (Alpine)
        # ./build-alpine-static-image.sh
        # #

        # # Build fully static image (Scratch)
        # ./build-static-image.sh
        # #

        # Download upx
        ./setup-upx.sh
        #

        # Build fully static compressed image (Scratch UPX)
        ./build-static-upx-image.sh
        #
        docker images webserver
